app:
  message: message succesfully sent
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    routingkey: user.routingkey
  data:
    mongodb:
      database: test_db
      port: 27017
      host: localhost
server:
  port: 8081