app:
  message: message succesfully sent
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    routingkey: user.routingkey
    publisher-confirm-type: correlated
    publisher-returns: true
server:
  port: 8081
